# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'options_menu.ui',
# licensing of 'options_menu.ui' applies.
#
# Created: Sun Nov  3 19:56:53 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Options_Menu(object):
    def setupUi(self, Options_Menu):
        Options_Menu.setObjectName("Options_Menu")
        Options_Menu.resize(800, 600)
        Options_Menu.setMaximumSize(QtCore.QSize(800, 600))
        self.tabWidget = QtWidgets.QTabWidget(Options_Menu)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.tabWidget.setMaximumSize(QtCore.QSize(800, 600))
        self.tabWidget.setObjectName("tabWidget")
        self.Content_Pack = QtWidgets.QWidget()
        self.Content_Pack.setMaximumSize(QtCore.QSize(800, 600))
        self.Content_Pack.setObjectName("Content_Pack")
        self.returnButton_4 = QtWidgets.QPushButton(self.Content_Pack)
        self.returnButton_4.setGeometry(QtCore.QRect(0, 550, 75, 23))
        self.returnButton_4.setObjectName("returnButton_4")
        self.label_3 = QtWidgets.QLabel(self.Content_Pack)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 51, 21))
        self.label_3.setObjectName("label_3")
        self.walkUpButton = QtWidgets.QPushButton(self.Content_Pack)
        self.walkUpButton.setGeometry(QtCore.QRect(110, 40, 75, 21))
        self.walkUpButton.setText("")
        self.walkUpButton.setObjectName("walkUpButton")
        self.label_4 = QtWidgets.QLabel(self.Content_Pack)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 71, 21))
        self.label_4.setObjectName("label_4")
        self.walkLeftButton = QtWidgets.QPushButton(self.Content_Pack)
        self.walkLeftButton.setGeometry(QtCore.QRect(110, 70, 75, 21))
        self.walkLeftButton.setText("")
        self.walkLeftButton.setObjectName("walkLeftButton")
        self.label_5 = QtWidgets.QLabel(self.Content_Pack)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 71, 21))
        self.label_5.setObjectName("label_5")
        self.walkDownButton = QtWidgets.QPushButton(self.Content_Pack)
        self.walkDownButton.setGeometry(QtCore.QRect(110, 130, 75, 21))
        self.walkDownButton.setText("")
        self.walkDownButton.setObjectName("walkDownButton")
        self.label_6 = QtWidgets.QLabel(self.Content_Pack)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 71, 21))
        self.label_6.setObjectName("label_6")
        self.walkRightButton = QtWidgets.QPushButton(self.Content_Pack)
        self.walkRightButton.setGeometry(QtCore.QRect(110, 100, 75, 21))
        self.walkRightButton.setText("")
        self.walkRightButton.setObjectName("walkRightButton")
        self.label_7 = QtWidgets.QLabel(self.Content_Pack)
        self.label_7.setGeometry(QtCore.QRect(10, 160, 71, 21))
        self.label_7.setObjectName("label_7")
        self.jumpButton = QtWidgets.QPushButton(self.Content_Pack)
        self.jumpButton.setGeometry(QtCore.QRect(110, 160, 75, 21))
        self.jumpButton.setText("")
        self.jumpButton.setObjectName("jumpButton")
        self.label_8 = QtWidgets.QLabel(self.Content_Pack)
        self.label_8.setGeometry(QtCore.QRect(10, 190, 71, 21))
        self.label_8.setObjectName("label_8")
        self.walkButton = QtWidgets.QPushButton(self.Content_Pack)
        self.walkButton.setGeometry(QtCore.QRect(110, 190, 75, 21))
        self.walkButton.setText("")
        self.walkButton.setObjectName("walkButton")
        self.label_9 = QtWidgets.QLabel(self.Content_Pack)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 61, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.Content_Pack)
        self.label_10.setGeometry(QtCore.QRect(10, 230, 61, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.Content_Pack)
        self.label_11.setGeometry(QtCore.QRect(10, 250, 81, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.Content_Pack)
        self.label_12.setGeometry(QtCore.QRect(10, 280, 101, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.Content_Pack)
        self.label_13.setGeometry(QtCore.QRect(10, 310, 81, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.Content_Pack)
        self.label_14.setGeometry(QtCore.QRect(10, 340, 81, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.Content_Pack)
        self.label_15.setGeometry(QtCore.QRect(10, 370, 81, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.Content_Pack)
        self.label_16.setGeometry(QtCore.QRect(10, 400, 81, 21))
        self.label_16.setObjectName("label_16")
        self.takeScreenButton = QtWidgets.QPushButton(self.Content_Pack)
        self.takeScreenButton.setGeometry(QtCore.QRect(110, 250, 75, 21))
        self.takeScreenButton.setText("")
        self.takeScreenButton.setObjectName("takeScreenButton")
        self.openBookButton = QtWidgets.QPushButton(self.Content_Pack)
        self.openBookButton.setGeometry(QtCore.QRect(110, 280, 75, 21))
        self.openBookButton.setText("")
        self.openBookButton.setObjectName("openBookButton")
        self.openFriendsButton = QtWidgets.QPushButton(self.Content_Pack)
        self.openFriendsButton.setGeometry(QtCore.QRect(110, 310, 75, 21))
        self.openFriendsButton.setText("")
        self.openFriendsButton.setObjectName("openFriendsButton")
        self.viewGagsButtons = QtWidgets.QPushButton(self.Content_Pack)
        self.viewGagsButtons.setGeometry(QtCore.QRect(110, 340, 75, 21))
        self.viewGagsButtons.setText("")
        self.viewGagsButtons.setObjectName("viewGagsButtons")
        self.viewToontasksButton = QtWidgets.QPushButton(self.Content_Pack)
        self.viewToontasksButton.setGeometry(QtCore.QRect(110, 370, 75, 21))
        self.viewToontasksButton.setText("")
        self.viewToontasksButton.setObjectName("viewToontasksButton")
        self.performActionButton = QtWidgets.QPushButton(self.Content_Pack)
        self.performActionButton.setGeometry(QtCore.QRect(110, 400, 75, 21))
        self.performActionButton.setText("")
        self.performActionButton.setObjectName("performActionButton")
        self.label_17 = QtWidgets.QLabel(self.Content_Pack)
        self.label_17.setGeometry(QtCore.QRect(10, 430, 81, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.Content_Pack)
        self.label_18.setGeometry(QtCore.QRect(10, 460, 81, 21))
        self.label_18.setObjectName("label_18")
        self.exitActivityButton = QtWidgets.QPushButton(self.Content_Pack)
        self.exitActivityButton.setGeometry(QtCore.QRect(110, 430, 75, 21))
        self.exitActivityButton.setText("")
        self.exitActivityButton.setObjectName("exitActivityButton")
        self.viewMapButton = QtWidgets.QPushButton(self.Content_Pack)
        self.viewMapButton.setGeometry(QtCore.QRect(110, 460, 75, 21))
        self.viewMapButton.setText("")
        self.viewMapButton.setObjectName("viewMapButton")
        self.label_19 = QtWidgets.QLabel(self.Content_Pack)
        self.label_19.setGeometry(QtCore.QRect(240, 10, 51, 21))
        self.label_19.setTextFormat(QtCore.Qt.AutoText)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.Content_Pack)
        self.label_20.setGeometry(QtCore.QRect(240, 40, 81, 21))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.Content_Pack)
        self.label_21.setGeometry(QtCore.QRect(240, 70, 81, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.Content_Pack)
        self.label_22.setGeometry(QtCore.QRect(240, 100, 81, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.Content_Pack)
        self.label_23.setGeometry(QtCore.QRect(240, 130, 81, 21))
        self.label_23.setObjectName("label_23")
        self.changeCameraButton = QtWidgets.QPushButton(self.Content_Pack)
        self.changeCameraButton.setGeometry(QtCore.QRect(340, 40, 75, 21))
        self.changeCameraButton.setText("")
        self.changeCameraButton.setObjectName("changeCameraButton")
        self.PreviousCameraButton = QtWidgets.QPushButton(self.Content_Pack)
        self.PreviousCameraButton.setGeometry(QtCore.QRect(340, 70, 75, 21))
        self.PreviousCameraButton.setText("")
        self.PreviousCameraButton.setObjectName("PreviousCameraButton")
        self.lookUpButton = QtWidgets.QPushButton(self.Content_Pack)
        self.lookUpButton.setGeometry(QtCore.QRect(340, 100, 75, 21))
        self.lookUpButton.setText("")
        self.lookUpButton.setObjectName("lookUpButton")
        self.lookDownButton = QtWidgets.QPushButton(self.Content_Pack)
        self.lookDownButton.setGeometry(QtCore.QRect(340, 130, 75, 21))
        self.lookDownButton.setText("")
        self.lookDownButton.setObjectName("lookDownButton")
        self.label_24 = QtWidgets.QLabel(self.Content_Pack)
        self.label_24.setGeometry(QtCore.QRect(230, 170, 81, 21))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.Content_Pack)
        self.label_25.setGeometry(QtCore.QRect(230, 190, 81, 21))
        self.label_25.setObjectName("label_25")
        self.line = QtWidgets.QFrame(self.Content_Pack)
        self.line.setGeometry(QtCore.QRect(200, 0, 261, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(self.Content_Pack)
        self.line_3.setGeometry(QtCore.QRect(200, 150, 261, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.Content_Pack)
        self.line_4.setGeometry(QtCore.QRect(450, 10, 20, 301))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_6 = QtWidgets.QFrame(self.Content_Pack)
        self.line_6.setGeometry(QtCore.QRect(0, 0, 201, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.Content_Pack)
        self.line_7.setGeometry(QtCore.QRect(190, 10, 16, 491))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.Content_Pack)
        self.line_8.setGeometry(QtCore.QRect(0, 210, 201, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.Content_Pack)
        self.line_9.setGeometry(QtCore.QRect(0, 490, 191, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.showAndHideButton = QtWidgets.QPushButton(self.Content_Pack)
        self.showAndHideButton.setGeometry(QtCore.QRect(340, 190, 75, 21))
        self.showAndHideButton.setText("")
        self.showAndHideButton.setObjectName("showAndHideButton")
        self.label_26 = QtWidgets.QLabel(self.Content_Pack)
        self.label_26.setGeometry(QtCore.QRect(230, 220, 91, 21))
        self.label_26.setObjectName("label_26")
        self.displayDebugButton = QtWidgets.QPushButton(self.Content_Pack)
        self.displayDebugButton.setGeometry(QtCore.QRect(340, 220, 75, 21))
        self.displayDebugButton.setText("")
        self.displayDebugButton.setObjectName("displayDebugButton")
        self.label_27 = QtWidgets.QLabel(self.Content_Pack)
        self.label_27.setGeometry(QtCore.QRect(230, 250, 91, 21))
        self.label_27.setObjectName("label_27")
        self.debugScreenButton = QtWidgets.QPushButton(self.Content_Pack)
        self.debugScreenButton.setGeometry(QtCore.QRect(340, 250, 75, 21))
        self.debugScreenButton.setText("")
        self.debugScreenButton.setObjectName("debugScreenButton")
        self.label_28 = QtWidgets.QLabel(self.Content_Pack)
        self.label_28.setGeometry(QtCore.QRect(230, 280, 61, 21))
        self.label_28.setObjectName("label_28")
        self.cogHQButton = QtWidgets.QPushButton(self.Content_Pack)
        self.cogHQButton.setGeometry(QtCore.QRect(340, 280, 75, 21))
        self.cogHQButton.setText("")
        self.cogHQButton.setObjectName("cogHQButton")
        self.line_5 = QtWidgets.QFrame(self.Content_Pack)
        self.line_5.setGeometry(QtCore.QRect(200, 300, 261, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.tabWidget.addTab(self.Content_Pack, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gameModes = QtWidgets.QComboBox(self.tab_4)
        self.gameModes.setGeometry(QtCore.QRect(100, 30, 161, 22))
        self.gameModes.setObjectName("gameModes")
        self.gameModes.addItem("")
        self.gameModes.addItem("")
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(0, 30, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(0, 60, 81, 16))
        self.label_2.setObjectName("label_2")
        self.ipAddress = QtWidgets.QLineEdit(self.tab_4)
        self.ipAddress.setGeometry(QtCore.QRect(100, 60, 161, 20))
        self.ipAddress.setObjectName("ipAddress")
        self.returnButton_5 = QtWidgets.QPushButton(self.tab_4)
        self.returnButton_5.setGeometry(QtCore.QRect(0, 550, 75, 23))
        self.returnButton_5.setObjectName("returnButton_5")
        self.label_29 = QtWidgets.QLabel(self.tab_4)
        self.label_29.setGeometry(QtCore.QRect(0, 10, 81, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_4)
        self.label_30.setGeometry(QtCore.QRect(0, 100, 101, 16))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab_4)
        self.label_31.setGeometry(QtCore.QRect(0, 120, 81, 16))
        self.label_31.setObjectName("label_31")
        self.DisplayMode = QtWidgets.QComboBox(self.tab_4)
        self.DisplayMode.setGeometry(QtCore.QRect(100, 120, 161, 22))
        self.DisplayMode.setToolTipDuration(4)
        self.DisplayMode.setObjectName("DisplayMode")
        self.DisplayMode.addItem("")
        self.DisplayMode.addItem("")
        self.DisplayMode.addItem("")
        self.label_32 = QtWidgets.QLabel(self.tab_4)
        self.label_32.setGeometry(QtCore.QRect(0, 150, 81, 16))
        self.label_32.setObjectName("label_32")
        self.resolutionBox = QtWidgets.QComboBox(self.tab_4)
        self.resolutionBox.setGeometry(QtCore.QRect(100, 150, 161, 22))
        self.resolutionBox.setObjectName("resolutionBox")
        self.resolutionBox.addItem("")
        self.resolutionBox.addItem("")
        self.resolutionBox.addItem("")
        self.resolutionBox.addItem("")
        self.resolutionBox.addItem("")
        self.resolutionBox.addItem("")
        self.resolutionBox.addItem("")
        self.resolutionBox.addItem("")
        self.resolutionBox.addItem("")
        self.resolutionBox.addItem("")
        self.resolutionBox.addItem("")
        self.resolutionBox.addItem("")
        self.resolutionBox.addItem("")
        self.label_33 = QtWidgets.QLabel(self.tab_4)
        self.label_33.setGeometry(QtCore.QRect(0, 190, 51, 16))
        self.label_33.setObjectName("label_33")
        self.fpsSlider = QtWidgets.QSlider(self.tab_4)
        self.fpsSlider.setGeometry(QtCore.QRect(100, 190, 21, 22))
        self.fpsSlider.setMaximum(1)
        self.fpsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.fpsSlider.setObjectName("fpsSlider")
        self.label_34 = QtWidgets.QLabel(self.tab_4)
        self.label_34.setGeometry(QtCore.QRect(0, 220, 51, 16))
        self.label_34.setObjectName("label_34")
        self.vSyncSlider = QtWidgets.QSlider(self.tab_4)
        self.vSyncSlider.setGeometry(QtCore.QRect(100, 220, 21, 22))
        self.vSyncSlider.setMaximum(1)
        self.vSyncSlider.setOrientation(QtCore.Qt.Horizontal)
        self.vSyncSlider.setObjectName("vSyncSlider")
        self.label_35 = QtWidgets.QLabel(self.tab_4)
        self.label_35.setGeometry(QtCore.QRect(0, 250, 51, 16))
        self.label_35.setObjectName("label_35")
        self.antiAliasingBox = QtWidgets.QComboBox(self.tab_4)
        self.antiAliasingBox.setGeometry(QtCore.QRect(100, 250, 161, 22))
        self.antiAliasingBox.setObjectName("antiAliasingBox")
        self.antiAliasingBox.addItem("")
        self.antiAliasingBox.addItem("")
        self.antiAliasingBox.addItem("")
        self.antiAliasingBox.addItem("")
        self.label_36 = QtWidgets.QLabel(self.tab_4)
        self.label_36.setGeometry(QtCore.QRect(0, 280, 71, 16))
        self.label_36.setObjectName("label_36")
        self.lodDistanceBox = QtWidgets.QComboBox(self.tab_4)
        self.lodDistanceBox.setGeometry(QtCore.QRect(100, 280, 161, 22))
        self.lodDistanceBox.setObjectName("lodDistanceBox")
        self.lodDistanceBox.addItem("")
        self.lodDistanceBox.addItem("")
        self.lodDistanceBox.addItem("")
        self.label_37 = QtWidgets.QLabel(self.tab_4)
        self.label_37.setGeometry(QtCore.QRect(0, 310, 91, 16))
        self.label_37.setObjectName("label_37")
        self.animationSlider = QtWidgets.QSlider(self.tab_4)
        self.animationSlider.setGeometry(QtCore.QRect(100, 310, 21, 22))
        self.animationSlider.setMaximum(1)
        self.animationSlider.setOrientation(QtCore.Qt.Horizontal)
        self.animationSlider.setObjectName("animationSlider")
        self.label_38 = QtWidgets.QLabel(self.tab_4)
        self.label_38.setGeometry(QtCore.QRect(0, 340, 91, 16))
        self.label_38.setObjectName("label_38")
        self.guiSlider = QtWidgets.QSlider(self.tab_4)
        self.guiSlider.setGeometry(QtCore.QRect(100, 340, 21, 22))
        self.guiSlider.setMaximum(1)
        self.guiSlider.setOrientation(QtCore.Qt.Horizontal)
        self.guiSlider.setObjectName("guiSlider")
        self.label_39 = QtWidgets.QLabel(self.tab_4)
        self.label_39.setGeometry(QtCore.QRect(0, 370, 91, 16))
        self.label_39.setObjectName("label_39")
        self.particleSlider = QtWidgets.QSlider(self.tab_4)
        self.particleSlider.setGeometry(QtCore.QRect(100, 370, 21, 22))
        self.particleSlider.setMaximum(1)
        self.particleSlider.setOrientation(QtCore.Qt.Horizontal)
        self.particleSlider.setObjectName("particleSlider")
        self.label_40 = QtWidgets.QLabel(self.tab_4)
        self.label_40.setGeometry(QtCore.QRect(0, 400, 91, 16))
        self.label_40.setObjectName("label_40")
        self.disableAccessoriesSlider = QtWidgets.QSlider(self.tab_4)
        self.disableAccessoriesSlider.setGeometry(QtCore.QRect(100, 400, 21, 22))
        self.disableAccessoriesSlider.setMaximum(1)
        self.disableAccessoriesSlider.setOrientation(QtCore.Qt.Horizontal)
        self.disableAccessoriesSlider.setObjectName("disableAccessoriesSlider")
        self.saveChangesButton = QtWidgets.QPushButton(self.tab_4)
        self.saveChangesButton.setGeometry(QtCore.QRect(100, 460, 161, 23))
        self.saveChangesButton.setObjectName("saveChangesButton")
        self.label_41 = QtWidgets.QLabel(self.tab_4)
        self.label_41.setGeometry(QtCore.QRect(0, 430, 91, 16))
        self.label_41.setObjectName("label_41")
        self.discordIntergration = QtWidgets.QSlider(self.tab_4)
        self.discordIntergration.setGeometry(QtCore.QRect(100, 430, 21, 22))
        self.discordIntergration.setMaximum(1)
        self.discordIntergration.setOrientation(QtCore.Qt.Horizontal)
        self.discordIntergration.setObjectName("discordIntergration")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.resource_Button = QtWidgets.QPushButton(self.tab_2)
        self.resource_Button.setGeometry(QtCore.QRect(290, 180, 181, 23))
        self.resource_Button.setObjectName("resource_Button")
        self.treeView = QtWidgets.QTreeView(self.tab_2)
        self.treeView.setGeometry(QtCore.QRect(0, 0, 801, 161))
        self.treeView.setObjectName("treeView")
        self.returnButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.returnButton_3.setGeometry(QtCore.QRect(0, 550, 75, 23))
        self.returnButton_3.setObjectName("returnButton_3")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Options_Menu)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Options_Menu)

    def retranslateUi(self, Options_Menu):
        Options_Menu.setWindowTitle(QtWidgets.QApplication.translate("Options_Menu", "Option Menu", None, -1))
        self.returnButton_4.setText(QtWidgets.QApplication.translate("Options_Menu", "Return", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Options_Menu", "Walking up", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Options_Menu", "Walking left", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Options_Menu", "Walking right", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Options_Menu", "Walking down", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Options_Menu", "Jump", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Options_Menu", "Walk", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Options_Menu", "<html><head/><body><p><span style=\" font-weight:600;\">Movement</span></p></body></html>", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Options_Menu", "<html><head/><body><p><span style=\" font-weight:600;\">Gameplay</span></p></body></html>", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Options_Menu", "Take screenshot", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Options_Menu", "Open Shticker Book", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Options_Menu", "Open Friend List", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("Options_Menu", "View Gags", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("Options_Menu", "View Toontasks", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("Options_Menu", "Perform Action", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("Options_Menu", "Exit Activity", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("Options_Menu", "View Street Map", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("Options_Menu", "<html><head/><body><p><span style=\" font-weight:600;\">Camera</span></p></body></html>", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("Options_Menu", "Change Camera", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("Options_Menu", "Previous Camera", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("Options_Menu", "Look Up", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("Options_Menu", "Look Down", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("Options_Menu", "<html><head/><body><p><span style=\" font-weight:600;\">Utilities</span></p></body></html>", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("Options_Menu", "Show/Hide GUI", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("Options_Menu", "Display Debug Info", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("Options_Menu", "Debug Screenshots", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("Options_Menu", "Cog HQ info", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Content_Pack), QtWidgets.QApplication.translate("Options_Menu", "Controls", None, -1))
        self.gameModes.setItemText(0, QtWidgets.QApplication.translate("Options_Menu", "Local", None, -1))
        self.gameModes.setItemText(1, QtWidgets.QApplication.translate("Options_Menu", "Server", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Options_Menu", "Gamemode", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Options_Menu", "IP Address", None, -1))
        self.returnButton_5.setText(QtWidgets.QApplication.translate("Options_Menu", "Return", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("Options_Menu", "<html><head/><body><p><span style=\" font-weight:600;\">Login settings</span></p></body></html>", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("Options_Menu", "<html><head/><body><p><span style=\" font-weight:600;\">Graphical Settings</span></p></body></html>", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("Options_Menu", "Display Mode", None, -1))
        self.DisplayMode.setItemText(2, QtWidgets.QApplication.translate("Options_Menu", "Windowed", None, -1))
        self.DisplayMode.setItemText(3, QtWidgets.QApplication.translate("Options_Menu", "Borderless", None, -1))
        self.DisplayMode.setItemText(4, QtWidgets.QApplication.translate("Options_Menu", "Fullscreen", None, -1))
        self.label_32.setText(QtWidgets.QApplication.translate("Options_Menu", "Resolution", None, -1))
        self.resolutionBox.setItemText(5, QtWidgets.QApplication.translate("Options_Menu", "1920 x 1080", None, -1))
        self.resolutionBox.setItemText(6, QtWidgets.QApplication.translate("Options_Menu", "1680 x 1050", None, -1))
        self.resolutionBox.setItemText(7, QtWidgets.QApplication.translate("Options_Menu", "1600 x 900", None, -1))
        self.resolutionBox.setItemText(8, QtWidgets.QApplication.translate("Options_Menu", "1400 x 1050", None, -1))
        self.resolutionBox.setItemText(9, QtWidgets.QApplication.translate("Options_Menu", "1366 x 768", None, -1))
        self.resolutionBox.setItemText(10, QtWidgets.QApplication.translate("Options_Menu", "1360 x 768", None, -1))
        self.resolutionBox.setItemText(11, QtWidgets.QApplication.translate("Options_Menu", "1280 x 768", None, -1))
        self.resolutionBox.setItemText(12, QtWidgets.QApplication.translate("Options_Menu", "1280 x 720", None, -1))
        self.resolutionBox.setItemText(13, QtWidgets.QApplication.translate("Options_Menu", "1152 x 872", None, -1))
        self.resolutionBox.setItemText(14, QtWidgets.QApplication.translate("Options_Menu", "1152 x 864", None, -1))
        self.resolutionBox.setItemText(15, QtWidgets.QApplication.translate("Options_Menu", "1024 x 768", None, -1))
        self.resolutionBox.setItemText(16, QtWidgets.QApplication.translate("Options_Menu", "1024 x 600", None, -1))
        self.resolutionBox.setItemText(17, QtWidgets.QApplication.translate("Options_Menu", "800 x 600", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("Options_Menu", "Show FPS", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("Options_Menu", "V-Sync", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("Options_Menu", "Antialising", None, -1))
        self.antiAliasingBox.setItemText(18, QtWidgets.QApplication.translate("Options_Menu", "Off", None, -1))
        self.antiAliasingBox.setItemText(19, QtWidgets.QApplication.translate("Options_Menu", "2x MSAA", None, -1))
        self.antiAliasingBox.setItemText(20, QtWidgets.QApplication.translate("Options_Menu", "4x MSAA", None, -1))
        self.antiAliasingBox.setItemText(21, QtWidgets.QApplication.translate("Options_Menu", "8x MSAA", None, -1))
        self.label_36.setText(QtWidgets.QApplication.translate("Options_Menu", "LOD Distance", None, -1))
        self.lodDistanceBox.setItemText(22, QtWidgets.QApplication.translate("Options_Menu", "Near", None, -1))
        self.lodDistanceBox.setItemText(23, QtWidgets.QApplication.translate("Options_Menu", "Far", None, -1))
        self.lodDistanceBox.setItemText(24, QtWidgets.QApplication.translate("Options_Menu", "Very Far", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("Options_Menu", "Animation Blending", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("Options_Menu", "GUI Animation", None, -1))
        self.label_39.setText(QtWidgets.QApplication.translate("Options_Menu", "Particle Effects", None, -1))
        self.label_40.setText(QtWidgets.QApplication.translate("Options_Menu", "Disable Accessories", None, -1))
        self.saveChangesButton.setText(QtWidgets.QApplication.translate("Options_Menu", "Save Changes", None, -1))
        self.label_41.setText(QtWidgets.QApplication.translate("Options_Menu", "Discord Integration", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtWidgets.QApplication.translate("Options_Menu", "Game settings", None, -1))
        self.resource_Button.setText(QtWidgets.QApplication.translate("Options_Menu", "Resource Folder", None, -1))
        self.returnButton_3.setText(QtWidgets.QApplication.translate("Options_Menu", "Return", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("Options_Menu", "Content Packs", None, -1))

